---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.devflow.io
  resources:
  - appdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.devflow.io
  resources:
  - appdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps.devflow.io
  resources:
  - appdeployments/status
  verbs:
  - get
  - patch
  - update
