apiVersion: apps.devflow.io/v1
kind: AppDeployment
metadata:
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/managed-by: kustomize
  name: appdeployment-sample
spec:
  # TODO(user): Add fields here
